-- =============================================================================
-- Starter exercise library (~150 common lifts). is_custom = false, created_by null.
-- Idempotent-ish: safe to re-run because we guard on name.
-- =============================================================================
insert into public.exercises (name, muscle_group, equipment, is_custom)
select v.name, v.muscle_group, v.equipment, false
from (values
  -- Chest
  ('Barbell Bench Press', 'Chest', 'Barbell'),
  ('Incline Barbell Bench Press', 'Chest', 'Barbell'),
  ('Decline Barbell Bench Press', 'Chest', 'Barbell'),
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Bench Press', 'Chest', 'Dumbbell'),
  ('Dumbbell Fly', 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Fly', 'Chest', 'Dumbbell'),
  ('Cable Crossover', 'Chest', 'Cable'),
  ('Pec Deck', 'Chest', 'Machine'),
  ('Machine Chest Press', 'Chest', 'Machine'),
  ('Push-Up', 'Chest', 'Bodyweight'),
  ('Dip (Chest)', 'Chest', 'Bodyweight'),
  ('Smith Machine Bench Press', 'Chest', 'Machine'),
  -- Back
  ('Deadlift', 'Back', 'Barbell'),
  ('Barbell Row', 'Back', 'Barbell'),
  ('Pendlay Row', 'Back', 'Barbell'),
  ('T-Bar Row', 'Back', 'Barbell'),
  ('Dumbbell Row', 'Back', 'Dumbbell'),
  ('Chest-Supported Row', 'Back', 'Machine'),
  ('Seated Cable Row', 'Back', 'Cable'),
  ('Lat Pulldown', 'Back', 'Cable'),
  ('Wide-Grip Lat Pulldown', 'Back', 'Cable'),
  ('Close-Grip Lat Pulldown', 'Back', 'Cable'),
  ('Pull-Up', 'Back', 'Bodyweight'),
  ('Chin-Up', 'Back', 'Bodyweight'),
  ('Straight-Arm Pulldown', 'Back', 'Cable'),
  ('Rack Pull', 'Back', 'Barbell'),
  ('Machine Row', 'Back', 'Machine'),
  ('Inverted Row', 'Back', 'Bodyweight'),
  ('Meadows Row', 'Back', 'Barbell'),
  -- Shoulders
  ('Overhead Press', 'Shoulders', 'Barbell'),
  ('Seated Dumbbell Press', 'Shoulders', 'Dumbbell'),
  ('Arnold Press', 'Shoulders', 'Dumbbell'),
  ('Machine Shoulder Press', 'Shoulders', 'Machine'),
  ('Dumbbell Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Cable Lateral Raise', 'Shoulders', 'Cable'),
  ('Machine Lateral Raise', 'Shoulders', 'Machine'),
  ('Front Raise', 'Shoulders', 'Dumbbell'),
  ('Rear Delt Fly', 'Shoulders', 'Dumbbell'),
  ('Reverse Pec Deck', 'Shoulders', 'Machine'),
  ('Face Pull', 'Shoulders', 'Cable'),
  ('Upright Row', 'Shoulders', 'Barbell'),
  ('Push Press', 'Shoulders', 'Barbell'),
  -- Biceps
  ('Barbell Curl', 'Biceps', 'Barbell'),
  ('EZ-Bar Curl', 'Biceps', 'Barbell'),
  ('Dumbbell Curl', 'Biceps', 'Dumbbell'),
  ('Incline Dumbbell Curl', 'Biceps', 'Dumbbell'),
  ('Hammer Curl', 'Biceps', 'Dumbbell'),
  ('Preacher Curl', 'Biceps', 'Barbell'),
  ('Cable Curl', 'Biceps', 'Cable'),
  ('Concentration Curl', 'Biceps', 'Dumbbell'),
  ('Spider Curl', 'Biceps', 'Dumbbell'),
  ('Machine Curl', 'Biceps', 'Machine'),
  -- Triceps
  ('Close-Grip Bench Press', 'Triceps', 'Barbell'),
  ('Triceps Pushdown', 'Triceps', 'Cable'),
  ('Rope Pushdown', 'Triceps', 'Cable'),
  ('Overhead Cable Extension', 'Triceps', 'Cable'),
  ('Skull Crusher', 'Triceps', 'Barbell'),
  ('Dumbbell Overhead Extension', 'Triceps', 'Dumbbell'),
  ('Dip (Triceps)', 'Triceps', 'Bodyweight'),
  ('Bench Dip', 'Triceps', 'Bodyweight'),
  ('Kickback', 'Triceps', 'Dumbbell'),
  ('Machine Triceps Extension', 'Triceps', 'Machine'),
  -- Quads
  ('Back Squat', 'Quads', 'Barbell'),
  ('Front Squat', 'Quads', 'Barbell'),
  ('High-Bar Squat', 'Quads', 'Barbell'),
  ('Hack Squat', 'Quads', 'Machine'),
  ('Leg Press', 'Quads', 'Machine'),
  ('Leg Extension', 'Quads', 'Machine'),
  ('Bulgarian Split Squat', 'Quads', 'Dumbbell'),
  ('Goblet Squat', 'Quads', 'Dumbbell'),
  ('Walking Lunge', 'Quads', 'Dumbbell'),
  ('Smith Machine Squat', 'Quads', 'Machine'),
  ('Step-Up', 'Quads', 'Dumbbell'),
  ('Sissy Squat', 'Quads', 'Bodyweight'),
  -- Hamstrings
  ('Romanian Deadlift', 'Hamstrings', 'Barbell'),
  ('Stiff-Leg Deadlift', 'Hamstrings', 'Barbell'),
  ('Lying Leg Curl', 'Hamstrings', 'Machine'),
  ('Seated Leg Curl', 'Hamstrings', 'Machine'),
  ('Nordic Curl', 'Hamstrings', 'Bodyweight'),
  ('Good Morning', 'Hamstrings', 'Barbell'),
  ('Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell'),
  ('Glute-Ham Raise', 'Hamstrings', 'Bodyweight'),
  -- Glutes
  ('Hip Thrust', 'Glutes', 'Barbell'),
  ('Glute Bridge', 'Glutes', 'Barbell'),
  ('Cable Kickback', 'Glutes', 'Cable'),
  ('Machine Hip Abduction', 'Glutes', 'Machine'),
  ('Machine Hip Adduction', 'Glutes', 'Machine'),
  ('Sumo Deadlift', 'Glutes', 'Barbell'),
  -- Calves
  ('Standing Calf Raise', 'Calves', 'Machine'),
  ('Seated Calf Raise', 'Calves', 'Machine'),
  ('Leg Press Calf Raise', 'Calves', 'Machine'),
  ('Dumbbell Calf Raise', 'Calves', 'Dumbbell'),
  -- Core
  ('Hanging Leg Raise', 'Core', 'Bodyweight'),
  ('Cable Crunch', 'Core', 'Cable'),
  ('Plank', 'Core', 'Bodyweight'),
  ('Ab Wheel Rollout', 'Core', 'Other'),
  ('Russian Twist', 'Core', 'Bodyweight'),
  ('Sit-Up', 'Core', 'Bodyweight'),
  ('Decline Crunch', 'Core', 'Bodyweight'),
  ('Machine Crunch', 'Core', 'Machine'),
  ('Hanging Knee Raise', 'Core', 'Bodyweight'),
  ('Dead Bug', 'Core', 'Bodyweight'),
  ('Pallof Press', 'Core', 'Cable'),
  -- Forearms
  ('Wrist Curl', 'Forearms', 'Barbell'),
  ('Reverse Wrist Curl', 'Forearms', 'Barbell'),
  ('Reverse Curl', 'Forearms', 'Barbell'),
  ('Farmer''s Carry', 'Forearms', 'Dumbbell'),
  ('Wrist Roller', 'Forearms', 'Other'),
  -- Traps
  ('Barbell Shrug', 'Traps', 'Barbell'),
  ('Dumbbell Shrug', 'Traps', 'Dumbbell'),
  ('Cable Shrug', 'Traps', 'Cable'),
  -- Olympic / Power
  ('Power Clean', 'Full Body', 'Barbell'),
  ('Clean and Jerk', 'Full Body', 'Barbell'),
  ('Snatch', 'Full Body', 'Barbell'),
  ('Clean Pull', 'Full Body', 'Barbell'),
  ('Hang Clean', 'Full Body', 'Barbell'),
  -- Conditioning
  ('Kettlebell Swing', 'Full Body', 'Kettlebell'),
  ('Burpee', 'Full Body', 'Bodyweight'),
  ('Box Jump', 'Quads', 'Bodyweight'),
  ('Battle Ropes', 'Full Body', 'Other'),
  ('Rowing Machine', 'Full Body', 'Machine'),
  ('Assault Bike', 'Full Body', 'Machine'),
  ('Treadmill Run', 'Cardio', 'Machine'),
  ('Stationary Bike', 'Cardio', 'Machine'),
  ('Stair Climber', 'Cardio', 'Machine'),
  ('Elliptical', 'Cardio', 'Machine'),
  ('Jump Rope', 'Cardio', 'Other'),
  ('Incline Treadmill Walk', 'Cardio', 'Machine'),
  -- More chest/back/shoulder variants to round out the library
  ('Floor Press', 'Chest', 'Barbell'),
  ('Spoto Press', 'Chest', 'Barbell'),
  ('Landmine Press', 'Shoulders', 'Barbell'),
  ('Z Press', 'Shoulders', 'Barbell'),
  ('Single-Arm Cable Row', 'Back', 'Cable'),
  ('Kroc Row', 'Back', 'Dumbbell'),
  ('Cable Pullover', 'Back', 'Cable'),
  ('Renegade Row', 'Back', 'Dumbbell'),
  ('Zercher Squat', 'Quads', 'Barbell'),
  ('Pin Squat', 'Quads', 'Barbell'),
  ('Belt Squat', 'Quads', 'Machine'),
  ('Reverse Lunge', 'Quads', 'Dumbbell'),
  ('Curtsy Lunge', 'Glutes', 'Dumbbell'),
  ('Single-Leg Hip Thrust', 'Glutes', 'Bodyweight'),
  ('Banded Lateral Walk', 'Glutes', 'Other'),
  ('Donkey Calf Raise', 'Calves', 'Machine'),
  ('Cable Hammer Curl', 'Biceps', 'Cable'),
  ('Bayesian Curl', 'Biceps', 'Cable'),
  ('JM Press', 'Triceps', 'Barbell'),
  ('Tate Press', 'Triceps', 'Dumbbell'),
  ('Cable Front Raise', 'Shoulders', 'Cable'),
  ('Seated Dumbbell Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Trap Bar Deadlift', 'Back', 'Barbell'),
  ('Trap Bar Carry', 'Forearms', 'Barbell'),
  ('Toes-to-Bar', 'Core', 'Bodyweight'),
  ('Cable Woodchopper', 'Core', 'Cable')
) as v(name, muscle_group, equipment)
where not exists (
  select 1 from public.exercises e where e.name = v.name and e.is_custom = false
);
